name: "Homarr"
description: "Homarr for Home Assistant"
url: https://github.com/chriss158/home-assistant-addons/homar
version: "1.0"
slug: "homarr_addon"
init: false
webui: http://[HOST]:[PORT:7575]
arch:
  - aarch64
  - amd64
ports:
  7575/tcp: 7575
ports_description:
  7575/tcp: Web interface
options:
  secret_encryption_key:
schema:
  secret_encryption_key: str
map:
  - type: addon_config
    read_only: false
    path: /appdata
startup: system  
