---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.8.2
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.8.2
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.8.2
codenotary:
  signer: edschbert@gmail.com
  base_image: edschbert@gmail.com
args:
  DDNS_UPDATER_VERSION: 2.9.0
