---
version: 1.0
slug: ddns-updater
name: DDNS Updater
init: false
description: >-
  Lightweight universal DDNS Updater
url: https://github.com/chriss158/addons/tree/master/ddns-updater
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: http://[HOST]:[PORT:8075]
ingress: true
ingress_port: 8000
panel_admin: true
panel_icon: mdi:dns-outline
map:
  - type: addon_config
    read_only: False
ports:
  8000/tcp: 8075
ports_description:
  8000/tcp: Web interface (Not required for Ingress)
options:
  period: 5m
  providers:
    - provider: custom
      domain: example.com
      url: "https://example.com/update?domain=example.com&host=@&username=username&client_key=client_key"
      ipv4key: ipv4
      ipv6key: ipv6
      success_regex: good
      ip_version: ipv4 or ipv6
      ipv6_suffix: ""
  log_level: info  
schema:
  period: str?
  update_cooldown_period: str?
  publicip_fetchers: list(all|http|dns)?
  publicip_http_providers: str?
  publicipv4_http_providers: str?
  publicipv6_http_providers: str?
  publicip_dns_providers: str?
  publicip_dns_timeout: str?
  resolver_address: str?
  shoutrrr_addresses: str?
  shoutrrr_default_title: str?
  providers:
    - provider: str
      domain: str?
      url: url?
      ipv4key: str?
      ipv6key: str?
      success_regex: str?
      ip_version: list(ipv4|ipv6|ipv4 or ipv6)?
      ipv6_suffix: str?
      zone_identifier: str?
      group: str?
      ttl: int?
      token: password?
      personal_access_token: password?
      username: str?
      password: password?
      api_key: password?
      secret: password?
      key: password?
      access_key_id: str?
      access_secret: password?
      secret_api_key: password?
  log_level: list(debug|info|warning|error)      
startup: system
host_network: true